// <auto-generated />
namespace Coin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class coin2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coin2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103091537336_coin2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
